### ISSUE TITLE
T-rex QMK firmware Issue

### ISSUE THREAD

**Issue by AbhinashPatro** [SylivanKenobi/t-rex#4]
I have built the board but am currently having issues compiling the firmware. 

1. There are two missing libraries named Cihibi- OS and chibios-contrib
2. There is a missing hal_adc_lld.h file in your repository which fails qmk cli while compiling 
3. Manually adding  keyboards/t_rex folder in local QMK  repo results in following error :
" platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c:188:20: error: 'WS2812_DI_PIN' undeclared (first use in this function); did you mean 'WS2812_TIMING'? "

Can you please look into syncing  your repo with QMK one

**Comment by SylivanKenobi** [comment]
Yeah I'll look into it

**Comment by SylivanKenobi** [comment]
So the way it looks 1 and 2 are connected which are easy to fix. I'm  currently looking into No. 3. The way it looks the rgb light config has either changed or has a bug. If you disable rgblight in the [info.json](https://github.com/SylivanKenobi/qmk_firmware/blob/master/keyboards/t_rex/info.json#L14) the error doesn't occur any more.

**Comment by SylivanKenobi** [comment]
It turns out that `rgblight.pin` is deprecated and is replaced with `ws2812.pin` in the info.json.  I couldn't find this change in the documentation only in the json schema. 

So I synced with the qmk repo, fixed the Cihibi Issue and fixed the ws2812 pin. Now everything should work. Could you please verify that it works for you?

I'm stocked someone built this keyboard! If find more Issues or just need help I'll gladly to help.

**Comment by AbhinashPatro** [comment]
Sure SylivanKenobi, Let me try this tomorrow and get back to you with more updates.

It's a pretty keyboard. People are interested in the T-rex board too.  :)

**Comment by AbhinashPatro** [comment]
The QMK software looks good and works better now. Now Porting to the vial/via begins :)

Thanks for the help
